# -*- coding: utf-8 -*-
"""fuel_effeciency_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yw4u3M7Ag97o-XYggf1lyRDYEtsk6yWo
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("model.pkl")
encoder = joblib.load("label_encoder.pkl")

st.title("Fuel Efficiency App")

car_name = st.text_input("Car Name")
horsepower = st.selectbox(
    "Horsepower",
    encoder["Horsepower"].classes_
)

displacement = st.selectbox(
    "Displacement",
    encoder["Displacement"].classes_
)

year = st.selectbox(
    "Model Year",
    encoder["Model year"].classes_
)

weight = st.number_input(
    "Weight of Vehicle",
    min_value=100,
    max_value=400
)

df = pd.DataFrame({
    "Car_name": [car_name],
    "Horsepower": [horsepower],
    "Displacement": [displacement],
    "Model year": [year],
    "Weight_of_vehicle": [weight]
})
